<h1>Security Policy </h1>
<span id="result_box" lang="en" xml:lang="en"><span title="a) Declaraci&oacute;n."><strong>a) Declaration.</strong><br />
<br />
</span><span title="WikiGlobal.com encripta autom&aacute;ticamente toda informaci&oacute;n transmitida desde el computador del Usuario a nuestros servidores utilizando el protocolo Secure Sockets Layer (SSL) con 128 bits de longitud de llave.">WikiGlobal.com   automatically encrypts all information transmitted from the User's   computer to our servers using the Secure Sockets Layer (SSL) with 128   bit key length. </span><span title="La informaci&oacute;n que llega a nuestro portal, es almacenada en servidores de un centro de datos que est&aacute; altamente protegido tanto f&iacute;sica como electr&oacute;nicamente.">The   information that comes to our site is stored on servers in a data   center that is highly protected physically and electronically. </span><span title="Los mecanismos est&aacute;ndar de seguridad mantienen los servidores detr&aacute;s de una barrera electr&oacute;nica de Firewalls, quedando la informaci&oacute;n s&oacute;lo disponible para Usuarios v&aacute;lidos.">The   standard security mechanisms maintain the servers behind an electronic    firewalls, leaving the information is only available for valid   Distributors. </span><span title="El up time del centro de datos es de 99.9% que es la disponibilidad que este ofrece para acceso al portal.">The up time of the data center is 99.9% which is the availability it offers to access the portal. </span><span title="Sin embargo, el Usuario declara y acepta que WikiGlobal.com no puede garantizar la disponibilidad, continuidad y/o calidad del servicio y declara conocer que por oa trav&eacute;s del Portal no necesariamente podr&aacute; satisfacer los requerimientos tenidos en vista por el Usuario para ingresar al mismo">However,   the User acknowledges and agrees that WikiGlobal.com can not guarantee   the availability, continuity and / or quality of service and   acknowledges that by or through the Site may not necessarily be taken to   satisfy the requirements given by the user to enter the same </span><span title=".">.<br />
<br />
</span><span title="b) Nombre de Usuario y Clave de Ingreso."><strong>b) Username and Password to Login.</strong><br />
<br />
</span><span title="Las cuentas de WikiGlobal.com est&aacute;n identificadas con un Sistema de Autenticaci&oacute;n, a trav&eacute;s de un nombre de Usuario y Clave Secreta de Ingreso para ser validadas.">WikiGlobal.com accounts are identified by an authentication system through your email and secret password  for validation. </span><span title="La Clave Secreta de Ingreso es de un m&iacute;nimo de 6 caracteres y puede ser cambiada en cualquier momento y cuantas veces se desee.">The Secret Password is a minimum of 6 characters and can be changed at any time and as often as desired. </span><span title="Las Claves de Ingreso est&aacute;n encriptadas directamente en la base de datos."> The Password are encrypted directly in the database. </span><span title="Series de Claves y llaves de encriptaci&oacute;n protegen estos datos de forma segura y le aseguran la total identificaci&oacute;n de quien realiza las transacciones o consultas.">Series   keys and encryption keys to protect data securely and assure the   complete identification of who performs transactions or queries.<br />
<br />
</span><span title="Si ocurren tres intentos consecutivos fallidos de ingresar a una cuenta con Claves err&oacute;neas, se activa un mecanismo autom&aacute;tico de seguridad que evita mediante bloqueos temporales el ingreso por razones de seguridad."><span id="result_box2" lang="en" xml:lang="en"><span title="Si ocurren tres intentos">If three consecutive unsuccessful attempts occur</span></span>   login  to an   account, it activates an automatic safety system that   prevents entry by security reasons. </span><span title="Si olvida su Clave, deber&aacute; responder la pregunta de seguridad que usted mismo ingres&oacute; al momento de registrarse.">If you forget your password, you must answer the security question you entered it when registering. </span><span title="Si la respuesta es correcta, se enviar&aacute; a la casilla de correo (e-mail) registrada en la cuenta personal, la Clave temporal, que deber&aacute; ser cambiada por usted.">If   the answer is correct, be sent to the mailbox (e-mail) registered in   the personal account, the temporary password, which must be changed by   you.<br />
<br />
</span><span title="c) Seguridad en las Formas de Pago."><strong>c) Security of Payment.</strong><br />
<br />
</span><span title="En nuestro portal encontrar&aacute;, b&aacute;sicamente tres formas de pago.">In our site you are able accept all mayor Credit and Debits </span><span title="Dep&oacute;sito directo en cuenta corriente, mediante boleta de dep&oacute;sito desde la p&aacute;gina de Usuario WikiGlobal.com, transferencia electr&oacute;nica de de fondos y con tarjetas de cr&eacute;dito bancario usando aplicaci&oacute;n Webpay (Tarjetas emitidas en Mexico) o Paypal (Tarjetas emitidas en el el extranjero).">Cards, VISA, MASTERCARD. The payment process is entirly administrate from a Canadian Company : Alertpay Inc. <a href="www.alertpay.com">www.alertpay.com</a><br />
<br />
</span><span title="Todos disponen de una soluci&oacute;n que utiliza protocolo de encriptaci&oacute;n de la informaci&oacute;n SSL de 128 bits de longitud de llave, permiti&eacute;ndole a los Usuarios enviar sus datos en forma segura y confidencial a trav&eacute;s de Internet.">
<hey> 
They use encryption protocol SSL 128 information bits   of key length, allowing users to send their data securely and   confidentially over the Internet. </span><span title="WikiGlobal.com no tiene acceso ni gestiona las transferencias siendo esta operaci&oacute;n realizada directamente por el recaudador masivo, en caso de usar Interfaz electr&oacute;nica.">WikiGlobal has no access to any of this transaccions. <a href="www.alertpay.com">www.alertpay.com</a>  manages this operation according our instrucctions.<br />
<br />
</span><span title="d) Consejos de Seguridad."><strong>d) Safety Tips.</strong><br />
<br />
</span><span title="Consideramos importante informarle de la existencia de una modalidad de fraude electr&oacute;nico conocido como 'Phishing', cuya finalidad es robar sus datos personales mediante correos electr&oacute;nicos, mensajes o llamados telef&oacute;nicos muy convincentes que pueden ser a nombre de WikiGlobal.com o alguna empresa relacionada, solicitando">We   consider important to inform you of the existence of a form of phishing   known as &quot;Phishing&quot;, whose purpose is to steal your personal   information through emails, messages or telephone calls can be very   convincing to WikiGlobal.com name or any related company, requesting </span><span title="datos como nombres de Usuario, Clave, c&eacute;dula de identidad, entre otros.">User data such as names, key, identification card, among others.<br />
<br />
</span><span title="Para evitar ser v&iacute;ctima de este tipo de fraudes, tenga siempre presente estos consejos:">To avoid falling victim to this type of fraud, keep these tips:<br />
<br />
</span><span title="Desconf&iacute;e.">Beware. </span><span title="No responda correos electr&oacute;nicos, mensajes o llamados telef&oacute;nicos que le soliciten informaci&oacute;n personal o de sus productos WikiGlobal.com (Libros, m&uacute;sica, aplicaciones computacionales, e-Business pack o c&oacute;digos de distribuci&oacute;n ), o que lo inviten a ingresar a trav&eacute;s de un link">Do   not answer emails, or phone calls that ask for personal or   WikiGlobal.com products or be invited to enter through a link </span><span title="a nuestra p&aacute;gina.">to our website. </span><span title="WikiGlobal.com no solicita este tipo de informaci&oacute;n a sus clientes, un funcionario de WikiGlobal.com NUNCA le pedir&aacute; su Clave personal.">WikiGlobal.com not request such information to his clients.  Wiki-Global NEVER ask for your password. </span><span title="Desconf&iacute;e de correos electr&oacute;nicos cuya procedencia desconozca, le sugerimos no abrirlos y eliminarlos de inmediato.">Be wary of emails whose provenance unknown, we suggest not to open them and remove them immediately. </span><span title="Si los lee, recomendamos no abrir archivos adjuntos, &eacute;sta es la forma m&aacute;s com&uacute;n de contaminar con virus o software malicioso un computador.">If   you read, recommend not to open attachments, this is the most common   form of contamination with viruses or malware a computer.<br />
<br />
</span><span title="Controle su Grupo de Distribuidores Autorizados o Calificados.">Check your  Distributors Network. </span><span title="No s&oacute;lo por seguridad sino adem&aacute;s por un buen criterio de orden, le recomendamos generarse el h&aacute;bito de ingresar constantemente a nuestro sitio Web para comprobar &uacute;ltimos Distribuidores Autorizados o Calificados ingresados en su grupo.">Not   only for safety but also a good sense of order, we recommend generated   the habit of constantly enter our website to see the new Independent Distributors  admitted to your group (Downlines).<br />
<br />
</span><span title="Ingrese al sitio siempre digitado www.WikiGlobal.com Ingrese a nuestro sitio Web para realizar sus transacciones siempre digitado www.WikiGlobal.com en la barra de direcciones de su navegador, no lo haga desde un v&iacute;nculo en el men&uacute; favoritos o desde enlaces (v&iacute;nculos">Enter in   the site typing www.wiki-global.com always  to make your   transactions using your   browser, do not do it from a link on the menu favorites or from links   </span><span title="o links) incluidos en correos electr&oacute;nicos, y evite ingresar desde lugares p&uacute;blicos."> included in emails, and avoid entering from public places.<br />
<br />
</span><span title="Cuide su Clave de Ingreso."> Take care of your Password</span><span title="Cuide su Clave de Ingreso, no la use para ingresar a otros sitios web, no la de a conocer a otras personas o incluso a funcionarios de WikiGlobal.com, y tampoco permita que su PC la guarde para facilitar el ingreso posteriormente.">, do not use it to enter other web sites, do not to   tell  others persons or even WikiGlobal&acute;s employees, do not let your computer   log in to facilitate the entry later. </span><span title="Por seguridad, le sugerimos cambiarla en nuestro sitio cada 2 &oacute; 3 meses.">For safety reasons, we suggest you change your password in our site every 2 or 3 months. </span><span title="Ante cualquier sospecha de que alguien obtuvo tu Clave personal, c&aacute;mbiala inmediatamente desde la secci&oacute;n 'Perfil Privado /Perfil Personal / Informaci&oacute;n de acceso a cuenta'.">Any   suspicion that someone got your password, change it immediately from   the &quot;Profile  / Account Access Information&quot;.<br />
<br />
</span><span title="En caso de dudas o fraude, envienos un correo a nuestra casilla soporte@CaptoMexico.">In case of doubt or fraud, email us at fraud@wiki-global.com.<br />
<br />
</span><span title="e) Medidas de seguridad y protecci&oacute;n de datos personales."><strong>e) Safety and protection of personal data.</strong><br />
<br />
</span><span title="WikiGlobal.com ha dispuesto estrictas medidas de seguridad para evitar la p&eacute;rdida, el uso o alteraci&oacute;n de los datos personales recolectados.">WikiGlobal.com has ordered strict security measures to prevent the loss, misuse or alteration of personal data collected. </span><span title="La informaci&oacute;n personal que WikiGlobal.com recolecta es almacenada electr&oacute;nicamente y en su protecci&oacute;n se utilizan medidas f&iacute;sicas, administrativas, contractuales y t&eacute;cnicas.">The   personal information collected is stored electronically WikiGlobal.com   and protection measures are used physical, administrative, contractual   and technical.<br />
<br />
</span><span title="La informaci&oacute;n de la Cuenta es accesible a trav&eacute;s de Internet s&oacute;lo a trav&eacute;s del uso del nombre de Usuario y la Clave de Ingreso.">Account information is accessible via the Internet only through the use of the Username (email) and Password to Login. </span><span title="Para proteger la confidencialidad de la informaci&oacute;n personal, el Usuario tiene que mantener su Clave de Ingreso en secreto y no compartirla con otras personas.">To   protect the confidentiality of personal information, the user must keep   your Password  in secret and not share it with others. </span><span title="El Usuario es responsable del uso que de WikiGlobal.com o de su informaci&oacute;n se haga con su Clave o n&uacute;mero por cualquier persona.">The User is responsible for the use of your information WikiGlobal.com  with your password or  by anyone.</span></span><br />
